version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend
