# Streamlit secrets configuration for Aura Command Pro
# This file contains sensitive API keys and should not be committed to version control

MAPBOX_API_KEY = "pk.eyJ1IjoiYWxnb3JpdGhteCIsImEiOiJjbTdob3lzNmwxYjliMmxzamppbDRqMHlhIn0.bBKjPrD_sp6RY5t2-AEnGQ"

# OpenWeatherMap API key for live weather integration
OPENWEATHERMAP_API_KEY = "demo_api_key_replace_with_real_key" 